{% set name = "trio-parallel" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 856b2bed2cd0bc6ffd786fdbc4d9b124231b076f6b96a99ed79b6d8d6edde84d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - trio >=0.18.0
    - cffi  # [win and python_impl != 'pypy']
    - attrs >=17.3.0
    - outcome
    - tblib

test:
  imports:
    - trio_parallel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://trio-parallel.readthedocs.io/
  license: MIT OR Apache-2.0
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT
  summary: 'trio-parallel: CPU parallelism for Trio'
  description: |
    Do you have CPU-bound work that just keeps slowing down
    your Trio event loop no matter what you try? Do you need
    to get all those cores humming at once? This is the library for you!
  doc_url: https://trio-parallel.readthedocs.io/
  dev_url: https://github.com/richardsheridan/trio-parallel

extra:
  recipe-maintainers:
    - carlodri
