{% set name = "trio-parallel" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7be741cf1ab925c97a5f6f334aee469c3e9c98124a0229b4ed2bfe8563940c13

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =>3.7
    - pip
  run:
    - python =>3.7
    - trio >=0.18.0
    - cffi
    - attrs >=17.3.0
    - outcome

test:
  imports:
    - trio_parallel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://trio-parallel.readthedocs.io/
  license: MIT OR Apache-2.0
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT
  summary: 'trio-parallel: CPU parallelism for Trio'
  description: |
    Do you have CPU-bound work that just keeps slowing down
    your Trio event loop no matter what you try? Do you need
    to get all those cores humming at once? This is the library for you!
  doc_url: https://trio-parallel.readthedocs.io/
  dev_url: https://github.com/richardsheridan/trio-parallel

extra:
  recipe-maintainers:
    - carlodri
