{% set name = "trio-parallel" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 472b92d547f43bf9095ee07003f19a52b39d5519a3ea1637d8ab8ed2fec596c5

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - trio >=0.18.0
    - cffi  # [win and python_impl != 'pypy']
    - attrs >=17.3.0
    - outcome
    - tblib

test:
  imports:
    - trio_parallel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://trio-parallel.readthedocs.io/
  license: MIT OR Apache-2.0
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT
  summary: 'trio-parallel: CPU parallelism for Trio'
  description: |
    Do you have CPU-bound work that just keeps slowing down
    your Trio event loop no matter what you try? Do you need
    to get all those cores humming at once? This is the library for you!
  doc_url: https://trio-parallel.readthedocs.io/
  dev_url: https://github.com/richardsheridan/trio-parallel

extra:
  recipe-maintainers:
    - carlodri
